# -*- coding: utf-8 -*-
"""Web_Scraping (Top 500 Movies)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieG0dpiBbKbIR2MHqKKAyxijIAvybV-d
"""

import requests, json, pandas as pd

HEADERS = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Referer":    "https://flickmetrix.com/movies",
    "Accept":     "application/json, text/plain, */*",
}

PARAMS = {
    "amazonRegion": "us", "cast": "", "comboScoreMax": 100, "comboScoreMin": 0,
    "countryCode": "us", "criticRatingMax": 100, "criticRatingMin": 0,
    "criticReviewsMax": 1000, "criticReviewsMin": 50, "currentPage": 0,
    "deviceID": 1, "director": "", "format": "movies", "genreAND": "false",
    "googleScoreMax": 100, "googleScoreMin": 0, "imdbRatingMax": 10,
    "imdbRatingMin": 0, "imdbVotesMax": 2800000, "imdbVotesMin": 10000,
    "inCinemas": "true", "includeDismissed": "false", "includeSeen": "false",
    "includeWantToWatch": "true", "isCastSearch": "false",
    "isDirectorSearch": "false", "isPersonSearch": "false", "language": "all",
    "letterboxdScoreMax": 100, "letterboxdScoreMin": 0,
    "letterboxdVotesMax": 2000000, "letterboxdVotesMin": 0,
    "metacriticRatingMax": 100, "metacriticRatingMin": 0,
    "metacriticReviewsMax": 100, "metacriticReviewsMin": 0,
    "onAmazonPrime": "false", "onAmazonVideo": "false", "onDVD": "false",
    "onNetflix": "false", "pageSize": 500, "path": "/movies", "person": "",  # ← 500
    "plot": "", "queryType": "GetFilmsToSieve", "searchTerm": "",
    "sharedUser": "", "sortOrder": "comboScoreDesc", "title": "", "token": "",
    "watchedRating": 0, "writer": "", "yearMax": 2026, "yearMin": 1900,
}

OUTPUT_CSV = "flickmetrix_top500_clean.csv"

# ── Whitelist: these films are never removed regardless of missing data ─────
WHITELIST = {"tt31193180"}  # Sinners (2025)

# ── Thresholds for row removal ─────────────────────────────────────────────
IMDB_VOTES_THRESHOLD       = 50_000
AUDIENCE_REVIEWS_THRESHOLD = 25_000
LETTERBOXD_VOTES_THRESHOLD = 30_000
IMDB_VOTES_OVERRIDE        = 100_000  # always keep if IMDb_Votes > this

# ── Fetch ──────────────────────────────────────────────────────────────────
print("Fetching top 500 films...")
r = requests.get("https://flickmetrix.com/api2/values/getFilms",
                 params=PARAMS, headers=HEADERS, timeout=30)
films = json.loads(r.json())
print(f"Films fetched: {len(films)}")

# ── Parse ──────────────────────────────────────────────────────────────────
def get_providers(providers):
    if not providers:
        return ""
    names = []
    for p in providers:
        name = p.get("Provider")
        if name and name not in names:
            names.append(name)
    return ", ".join(names)

def parse_film(raw):
    imdb_raw = raw.get("imdbRating")
    imdb_100 = round(imdb_raw * 10, 1) if imdb_raw is not None else None
    return {
        "Title":             raw.get("Title"),
        "Year":              raw.get("Year"),
        "Genre":             raw.get("Genre"),
        "Director":          raw.get("Director"),
        "Cast":              raw.get("Cast"),
        "Language":          raw.get("Language"),
        "Plot":              raw.get("Plot"),
        "Awards":            raw.get("Awards"),
        "Production":        raw.get("Production"),
        "Flickmetrix_Score": raw.get("ComboScore"),
        "IMDb_10":           imdb_raw,
        "IMDb_100":          imdb_100,
        "IMDb_Votes":        raw.get("imdbVotes"),
        "Metacritic":        raw.get("MetacriticRating"),
        "Critic_Rating_RT":  raw.get("CriticRating"),
        "Critic_Reviews":    raw.get("CriticReviews"),
        "Audience_Rating":   raw.get("AudienceRating"),
        "Audience_Reviews":  raw.get("AudienceReviews"),
        "Letterboxd":        raw.get("LetterboxdScore"),
        "Letterboxd_Votes":  raw.get("letterboxdVotes"),
        "Google_Score":      raw.get("GoogleScore"),
        "Streaming_On":      get_providers(raw.get("Providers")),
        "RT_URL":            raw.get("RTUrl"),
        "imdbID":            raw.get("imdbID"),
    }

df = pd.DataFrame([parse_film(f) for f in films])
df = df.drop_duplicates(subset=["Title", "Year"])
print(f"After dedup: {len(df)}")

# ── Custom Combined Score ──────────────────────────────────────────────────
score_cols = ["IMDb_100", "Metacritic", "Critic_Rating_RT",
              "Audience_Rating", "Letterboxd", "Google_Score"]
df["Custom_Score"] = df[score_cols].mean(axis=1).round(2)

# ── Row Quality Filter ─────────────────────────────────────────────────────
def should_remove(row):
    # Whitelisted films: never remove
    if row["imdbID"] in WHITELIST:
        return False
    # Always keep if IMDb_Votes > override threshold
    if row["IMDb_Votes"] > IMDB_VOTES_OVERRIDE:
        return False
    # Count how many volume columns are below threshold or missing
    low_count = 0
    if pd.isna(row["IMDb_Votes"])       or row["IMDb_Votes"]       < IMDB_VOTES_THRESHOLD:
        low_count += 1
    if pd.isna(row["Audience_Reviews"]) or row["Audience_Reviews"] < AUDIENCE_REVIEWS_THRESHOLD:
        low_count += 1
    if pd.isna(row["Letterboxd_Votes"]) or row["Letterboxd_Votes"] < LETTERBOXD_VOTES_THRESHOLD:
        low_count += 1
    return low_count >= 2

mask_remove = df.apply(should_remove, axis=1)
print(f"\nRows removed: {mask_remove.sum()}")
for _, row in df[mask_remove].iterrows():
    print(f"  ✗ {row['Title']} ({int(row['Year'])})  IMDb_Votes={row['IMDb_Votes']:,.0f}")

df = df[~mask_remove].reset_index(drop=True)
print(f"Films after filter: {len(df)}")

# ── Sort & rank ────────────────────────────────────────────────────────────
df = df.sort_values("Custom_Score", ascending=False).reset_index(drop=True)
df.index = df.index + 1
df.index.name = "Rank"

top500 = df.head(500)
top500.to_csv(OUTPUT_CSV)

print(f"\n✅ Saved {len(top500)} movies → {OUTPUT_CSV}")
print("\nTop 20:")
preview = ["Title", "Year", "Custom_Score",
           "IMDb_10", "Metacritic", "Critic_Rating_RT",
           "Audience_Rating", "Letterboxd", "Google_Score"]
print(top500[preview].head(20).to_string())

from google.colab import files
files.download(OUTPUT_CSV)